version: "3.7"

services:
  proxy-server:
    container_name: proxy-server
    image: bunkerity/bunkerized-nginx
    restart: always
    environment:
      - MULTISITE=yes
      - SERVER_NAME=api.example.com www.example.com
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - AUTO_LETS_ENCRYPT=yes
      - USE_PROXY_CACHE=yes
      - USE_GZIP=yes
      - USE_BROTLI=yes
      - USE_REVERSE_PROXY=yes
      - api.gomi.land_REVERSE_PROXY_URL=/
      - api.gomi.land_REVERSE_PROXY_HOST=http://backend:4000/graphql
      - www.gomi.land_REVERSE_PROXY_URL=/
      - www.gomi.land_REVERSE_PROXY_HOST=http://frontend:8080
    networks:
      - webnet
    volumes:
      - ./certfiles:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    ports:
      - 80:8080
      - 443:8443

  redis:
    container_name: redis
    image: redis
    restart: always
    networks:
      - webnet

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER={{USER}}
      - POSTGRES_PASSWORD={{PASSWORD}}
      - POSTGRES_DB={{DB}}
    ports:
      - 4321:5432
    networks:
      - webnet
    volumes:
      - db-volume:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./api
    networks:
      - webnet
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER={{USER}}
      - DB_PASSWORD={{PASSWORD}}
      - DB_NAME={{DB}}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET_KEY={{SECRET_KEY}}
      - KAKAO_API_KEY={{KAKAO_API_KEY}}
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    networks:
      - webnet
    restart: always

networks:
  webnet:

volumes:
  db-volume:
